### ISSUE TITLE
Wrap around

### ISSUE THREAD

**Issue by otommod** [PeterRincker/vim-argumentative#11]
Basically, if you have `foo(a, b, c)`, with your cursor on the `c`, `>,` should move it before the `a`, like `foo(c, a, b)`.
Moreover, the way the plugin works right now, if your cursor is on the `)`, hitting `],` should put it on the `(`.

I don't know how easy it would be to implement this, but it'd be a much-welcomed addition!

**Comment by PeterRincker** [comment]
I personally like to do `99>,` to move an argument to the last position. I will have to ponder on this to think which is the best path for the plugin. However `99<,` should get he argument to the first position

**Comment by otommod** [comment]
Sorry for the late reply.

I haven't actually thought about using ranges... Since that is available, then my request is of less importance. It'd still be a cool feature to have I think, but I agree that the semantics would get a bit messed up...
