### ISSUE TITLE
vim-argumentative misbehaves with set selection=exclusive

### ISSUE THREAD

**Issue by mattiasflodin** [PeterRincker/vim-argumentative#4]
If you set selection=exclusive then the a, and i, text objects seem to miss one character on the right-hand side. This also makes shifting of arguments move everything except the last character of the argument name.

**Comment by PeterRincker** [comment]
Please review the sel_exclusive branch and see if that fixes this issue.

**Comment by mattiasflodin** [comment]
Yes that fixes it. I tested with selection=inclusive and selection=exclusive. Good work!
