### ISSUE TITLE
Moving arguments in ruby is misbehaving.

### ISSUE THREAD

**Issue by aaronbieber** [PeterRincker/vim-argumentative#5]
My regex-fu isn't as strong as I thought it was, but the plugin source looks as though it ought to handle this case, and yet I'm getting weird behavior, so I thought I'd post this issue and see if there is any chance it's my config or if it's a legit bug.

Moving arguments in PHP works perfectly, but moving them in ruby causes some odd behavior. For my tests I was working with files whose filetype was set to either "php" or "ruby" appropriately. Given this text:

``` ruby
def whatever(first, second, third, fourth)
end
```

If I place my cursor on "first" and press `>,`, the cursor jumps back to the "w" in "whatever." Weird... If I place my cursor on "second" and press `<,`, I get this:

``` ruby
desecondhatever(first, f w, third, fourth)
end
```

I can move "second" forward, and I can move "third" backwards, so it seems like the parentheses aren't getting picked up as boundaries even though my brief glance at the complex regex looked like they ought to be, but I only spent a short time.

Let me know if I can provide any other details.

**Comment by PeterRincker** [comment]
I added experimental support for ruby's implicit function parameters awhile ago. It appears that this experimental code path is being used when it shouldn't. I will have to review my implicit function call detection in order to fix this issue.

**Comment by PeterRincker** [comment]
I have modified the implicit function call regex to ignore function declarations. Please check out branch [issue5](https://github.com/PeterRincker/vim-argumentative/tree/issue5) and test it out on your ruby files.

**Comment by sarahzrf** [comment]
I am also experiencing this issue, and it _is_ fixed on branch issue5. Why not merge it back?

**Comment by PeterRincker** [comment]
Thank you for testing this for me. I have merged it back
