### ISSUE TITLE
Facing a weird issue with mapping ],

### ISSUE THREAD

**Issue by dhruvasagar** [PeterRincker/vim-argumentative#7]
Hi,

This is most likely not an issue of the plugin itself, might even be a bug in vim, but would like your help figuring it out. This is what I see in my setup, this is a problem only for <kbd>],</kbd> mapping, others are working fine.

``` vim
:echo hasmapto('],', 'n') => 1
:echo maparg('],', 'n') => ''
:echo len(maparg('],', 'n')) => 0
:echo empty(maparg('],', 'n')) => 1
:map ], => no mappings
```

As a result the mapping for <kbd>],</kbd> is not defined since you use `hasmapto()`

**Comment by PeterRincker** [comment]
I believe something interfering with your `],` mapping. This is what i get:

``` vim
:echo maparg('],', 'n') => <Plug>Argumentative_Next
```

I would suggest you take a look at your `~/.vimrc` file or disable plugins to see what is interfering with that mapping.

**Comment by dhruvasagar** [comment]
but there is no mapping with <kbd>[,</kbd>...

**Comment by PeterRincker** [comment]
Argumentative checks to see if there is already a mapping, via `hasmapto()`, before it assigns it to one of the `<Plug>Argumentative_` mappings. However it seems like you are using [NeoBundle's lazy loading](https://github.com/dhruvasagar/dotfiles/blob/master/vim/neo_bundles.vim#L203).  I am unfamiliar with NeoBundle however I would try something like this:

``` vim
NeoBundleLazy 'PeterRincker/vim-argumentative', {
      \ 'autoload': {
      \   'mappings': [
      \    ['<Plug>Argumentative_'],
      \   ]
      \ }
      \}
```

**Comment by dhruvasagar** [comment]
I have tried with both lazy loading and normal loading, so that's not an issue. I'll probably test it out more sometime later.
